import { PropsWithChildren } from "react";

export const metadata = {
  title: "Inicio",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
